package com.kakeibo.android.core.database.entity

import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Local replica schema (database_design.md §5). Each entity mirrors the backend Postgres
 * table 1:1 for the fields delivered by `GET /sync/pull`, plus the local-only sync
 * bookkeeping columns from §5.2 ([SyncMeta]).
 *
 * Tag join tables (transaction_tags etc.) are intentionally omitted in Phase 2: the sync
 * pull does not deliver tag associations (SyncService returns `tags = emptyList()`), so they
 * are modelled in a later phase together with the CRUD write paths that need them.
 */

/** Local-only sync bookkeeping embedded in every replicated entity (design doc §5.2). */
data class SyncMeta(
    @ColumnInfo(name = "is_synced") val isSynced: Boolean = true,
    @ColumnInfo(name = "sync_status") val syncStatus: String = SyncStatus.CLEAN,
    @ColumnInfo(name = "local_updated_at") val localUpdatedAt: Long = 0L,
)

object SyncStatus {
    const val CLEAN = "clean"
    const val PENDING = "pending"
    const val CONFLICT = "conflict"

    /**
     * An undo-window soft-delete whose push is deliberately deferred: the row is hidden from the UI
     * immediately but is *not* pushed (excluded from `dirty()`) until the undo window closes and it
     * is promoted to [PENDING]. This keeps a background/periodic sync from pushing a delete the user
     * may still undo.
     */
    const val PENDING_DELETE = "pending_delete"
}

@Entity(tableName = "accounts")
data class AccountEntity(
    @PrimaryKey val id: String,
    val name: String,
    val type: String,
    @ColumnInfo(name = "initial_balance") val initialBalance: Long,
    val currency: String,
    @ColumnInfo(name = "sort_order") val sortOrder: Int,
    @ColumnInfo(name = "payment_day") val paymentDay: Int?,
    val balance: Long,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

@Entity(tableName = "categories")
data class CategoryEntity(
    @PrimaryKey val id: String,
    val name: String,
    val type: String,
    val icon: String?,
    val color: String?,
    @ColumnInfo(name = "sort_order") val sortOrder: Int,
    @ColumnInfo(name = "is_default") val isDefault: Boolean,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

@Entity(tableName = "tags")
data class TagEntity(
    @PrimaryKey val id: String,
    val name: String,
    val color: String?,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

@Entity(tableName = "transactions")
data class TransactionEntity(
    @PrimaryKey val id: String,
    val name: String?,
    val type: String,
    val amount: Long,
    val currency: String,
    val date: String,
    val memo: String?,
    @ColumnInfo(name = "category_id") val categoryId: String?,
    @ColumnInfo(name = "account_id") val accountId: String?,
    @ColumnInfo(name = "is_auto_generated") val isAutoGenerated: Boolean,
    @ColumnInfo(name = "is_balance_adjustment") val isBalanceAdjustment: Boolean,
    @ColumnInfo(name = "recurring_transaction_id") val recurringTransactionId: String?,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

@Entity(tableName = "transfers")
data class TransferEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "from_account_id") val fromAccountId: String,
    @ColumnInfo(name = "to_account_id") val toAccountId: String,
    val amount: Long,
    val currency: String,
    val date: String,
    val memo: String?,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

@Entity(tableName = "templates")
data class TemplateEntity(
    @PrimaryKey val id: String,
    val name: String,
    @ColumnInfo(name = "transaction_name") val transactionName: String?,
    val type: String,
    val amount: Long?,
    val currency: String,
    @ColumnInfo(name = "category_id") val categoryId: String?,
    @ColumnInfo(name = "account_id") val accountId: String?,
    val memo: String?,
    @ColumnInfo(name = "use_count") val useCount: Int,
    @ColumnInfo(name = "last_used_at") val lastUsedAt: String?,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

@Entity(tableName = "recurring_transactions")
data class RecurringTransactionEntity(
    @PrimaryKey val id: String,
    val type: String,
    val amount: Long,
    val currency: String,
    @ColumnInfo(name = "category_id") val categoryId: String,
    @ColumnInfo(name = "account_id") val accountId: String,
    val memo: String?,
    val frequency: String,
    @ColumnInfo(name = "interval") val interval: Int,
    @ColumnInfo(name = "day_of_week") val dayOfWeek: Int?,
    @ColumnInfo(name = "day_of_month") val dayOfMonth: Int?,
    @ColumnInfo(name = "month_of_year") val monthOfYear: Int?,
    @ColumnInfo(name = "start_date") val startDate: String,
    @ColumnInfo(name = "end_date") val endDate: String?,
    @ColumnInfo(name = "next_execution_date") val nextExecutionDate: String,
    @ColumnInfo(name = "is_active") val isActive: Boolean,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

@Entity(tableName = "budgets")
data class BudgetEntity(
    @PrimaryKey val id: String,
    @ColumnInfo(name = "category_id") val categoryId: String,
    @ColumnInfo(name = "year_month") val yearMonth: String,
    val amount: Long,
    val currency: String,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @ColumnInfo(name = "deleted_at") val deletedAt: String?,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

/**
 * The sync API does not expose `deleted_at` for notification settings (it is absent from the
 * DTO, even though the backend table has the column), so this replica carries no soft-delete
 * field and observeAll returns every row. Notification settings are fixed per-type rows created
 * at setup and are not deleted in practice.
 */
@Entity(tableName = "notification_settings")
data class NotificationSettingEntity(
    @PrimaryKey val id: String,
    val type: String,
    @ColumnInfo(name = "is_enabled") val isEnabled: Boolean,
    val frequency: String?,
    @ColumnInfo(name = "day_of_week") val dayOfWeek: String?,
    @ColumnInfo(name = "time_of_day") val timeOfDay: String?,
    @ColumnInfo(name = "threshold_percent") val thresholdPercent: Int?,
    @ColumnInfo(name = "reminder_days_before") val reminderDaysBefore: Int?,
    val version: Int,
    @ColumnInfo(name = "created_at") val createdAt: String,
    @ColumnInfo(name = "updated_at") val updatedAt: String,
    @Embedded val sync: SyncMeta = SyncMeta(),
)

/** Input patterns are delivered without version/timestamp metadata (see DTO). */
@Entity(tableName = "input_patterns")
data class InputPatternEntity(
    @PrimaryKey val id: String,
    val keyword: String,
    @ColumnInfo(name = "category_id") val categoryId: String?,
    @ColumnInfo(name = "account_id") val accountId: String?,
    @ColumnInfo(name = "hit_count") val hitCount: Int,
    @ColumnInfo(name = "last_used_at") val lastUsedAt: String,
    @Embedded val sync: SyncMeta = SyncMeta(),
)
