package com.kakeibo.android.core.data.transaction

import androidx.paging.Pager
import androidx.paging.PagingConfig
import androidx.paging.PagingData
import com.kakeibo.android.core.data.sync.SyncScheduler
import com.kakeibo.android.core.database.dao.AccountDao
import com.kakeibo.android.core.database.dao.CategoryDao
import com.kakeibo.android.core.database.dao.TemplateDao
import com.kakeibo.android.core.database.dao.TransactionDao
import com.kakeibo.android.core.database.dao.TransactionListItem
import com.kakeibo.android.core.database.entity.AccountEntity
import com.kakeibo.android.core.database.entity.CategoryEntity
import com.kakeibo.android.core.database.entity.TemplateEntity
import com.kakeibo.android.core.database.entity.SyncMeta
import com.kakeibo.android.core.database.entity.SyncStatus
import com.kakeibo.android.core.database.entity.TransactionEntity
import kotlinx.coroutines.flow.Flow
import java.time.OffsetDateTime
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

/** Sort options for the transaction list; [key] matches [TransactionDao.pagingSource]'s sortKey. */
enum class TransactionSort(val key: Int) {
    DATE_DESC(0), DATE_ASC(1), AMOUNT_DESC(2), AMOUNT_ASC(3),
}

/** Active filter/sort for the paged transaction list. Null fields are skipped by the query. */
data class TransactionFilter(
    val keyword: String? = null,
    val type: String? = null,
    val categoryId: String? = null,
    val accountId: String? = null,
    val dateFrom: String? = null,
    val dateTo: String? = null,
    val sort: TransactionSort = TransactionSort.DATE_DESC,
)

/** Form payload for creating/updating a transaction. `date` is an ISO-local datetime string. */
data class TransactionInput(
    val type: String,
    val amount: Long,
    val date: String,
    val categoryId: String?,
    val accountId: String?,
    val name: String?,
    val memo: String?,
    val currency: String = "JPY",
)

/**
 * Offline-first transaction CRUD (design §3.1). All writes land in Room as the source of truth
 * with `sync_status = pending`, then [SyncScheduler] flushes them to the server when online.
 * Local creates start at `version = 0` (the server assigns 1 on first push); edits keep the base
 * version so the optimistic-lock check has something to compare against.
 */
@Singleton
class TransactionRepository @Inject constructor(
    private val transactionDao: TransactionDao,
    private val categoryDao: CategoryDao,
    private val accountDao: AccountDao,
    private val templateDao: TemplateDao,
    private val syncScheduler: SyncScheduler,
) {

    fun pagedTransactions(filter: TransactionFilter): Flow<PagingData<TransactionListItem>> =
        Pager(PagingConfig(pageSize = PAGE_SIZE, enablePlaceholders = false)) {
            transactionDao.pagingSource(
                keyword = filter.keyword?.takeIf { it.isNotBlank() }?.let(::escapeLikeArg),
                type = filter.type,
                categoryId = filter.categoryId,
                accountId = filter.accountId,
                dateFrom = filter.dateFrom,
                dateTo = filter.dateTo,
                sortKey = filter.sort.key,
            )
        }.flow

    fun observeTransaction(id: String): Flow<TransactionEntity?> = transactionDao.observeById(id)

    fun observeCategories(): Flow<List<CategoryEntity>> = categoryDao.observeAll()

    fun observeAccounts(): Flow<List<AccountEntity>> = accountDao.observeAll()

    suspend fun getTransaction(id: String): TransactionEntity? = transactionDao.getById(id)

    /** Loads a template for prefilling a new transaction (quick-add from dashboard/list). */
    suspend fun getTemplate(id: String): TemplateEntity? = templateDao.getById(id)

    suspend fun createTransaction(input: TransactionInput) {
        val now = OffsetDateTime.now().toString()
        transactionDao.upsert(
            TransactionEntity(
                id = UUID.randomUUID().toString(),
                name = input.name,
                type = input.type,
                amount = input.amount,
                currency = input.currency,
                date = input.date,
                memo = input.memo,
                categoryId = input.categoryId,
                accountId = input.accountId,
                isAutoGenerated = false,
                isBalanceAdjustment = false,
                recurringTransactionId = null,
                version = 0,
                createdAt = now,
                updatedAt = now,
                deletedAt = null,
                sync = SyncMeta(
                    isSynced = false,
                    syncStatus = SyncStatus.PENDING,
                    localUpdatedAt = System.currentTimeMillis(),
                ),
            )
        )
        syncScheduler.requestSync()
    }

    suspend fun updateTransaction(id: String, input: TransactionInput) {
        val existing = transactionDao.getById(id) ?: return
        transactionDao.upsert(
            existing.copy(
                name = input.name,
                type = input.type,
                amount = input.amount,
                currency = input.currency,
                date = input.date,
                memo = input.memo,
                categoryId = input.categoryId,
                accountId = input.accountId,
                updatedAt = OffsetDateTime.now().toString(),
                // version is left at the base value: the push sends it as client_version.
                sync = existing.sync.copy(
                    isSynced = false,
                    syncStatus = SyncStatus.PENDING,
                    localUpdatedAt = System.currentTimeMillis(),
                ),
            )
        )
        syncScheduler.requestSync()
    }

    /**
     * Hides a transaction locally for the undo window without contacting the server. A never-synced
     * local create (`version == 0`) is hard-deleted outright (the server never saw it); a synced row
     * is soft-deleted and flagged [SyncStatus.PENDING_DELETE], which keeps it out of `dirty()` so a
     * background/periodic sync cannot push the delete during the undo window. Returns the pre-delete
     * snapshot for [restore]; the push is promoted to pending by [commitDelete] once undo closes.
     */
    suspend fun softDeleteLocal(id: String): TransactionEntity? {
        val snapshot = transactionDao.getById(id) ?: return null
        if (snapshot.version == 0) {
            transactionDao.hardDelete(id)
        } else {
            transactionDao.upsert(
                snapshot.copy(
                    deletedAt = OffsetDateTime.now().toString(),
                    sync = snapshot.sync.copy(
                        isSynced = false,
                        syncStatus = SyncStatus.PENDING_DELETE,
                        localUpdatedAt = System.currentTimeMillis(),
                    ),
                )
            )
        }
        return snapshot
    }

    /** Reverts a [softDeleteLocal] by restoring the original row. No server round-trip. */
    suspend fun restore(snapshot: TransactionEntity) {
        transactionDao.upsert(snapshot)
    }

    /**
     * Commits a deferred soft-delete: promotes it from `pending_delete` to a pushable `pending` and
     * flushes. A no-op (no sync requested) when there is nothing to promote — e.g. a never-synced
     * create that was hard-deleted, or a row already restored via undo.
     */
    suspend fun commitDelete(id: String) {
        if (transactionDao.markDeleteCommitted(id) > 0) syncScheduler.requestSync()
    }

    private companion object {
        const val PAGE_SIZE = 50
    }
}

/**
 * Escapes LIKE wildcards so a literal `%` or `_` in the search term isn't treated as a pattern.
 * Paired with `ESCAPE '\'` in [com.kakeibo.android.core.database.dao.TransactionDao.pagingSource].
 */
private fun escapeLikeArg(raw: String): String =
    raw.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
