package com.kakeibo.android.core.data.transaction

import androidx.room.Room
import com.kakeibo.android.core.data.sync.SyncScheduler
import com.kakeibo.android.core.database.CashflowDatabase
import com.kakeibo.android.core.database.dao.TransactionDao
import com.kakeibo.android.core.database.entity.SyncMeta
import com.kakeibo.android.core.database.entity.SyncStatus
import com.kakeibo.android.core.database.entity.TransactionEntity
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.annotation.Config

/**
 * Covers the deferred-commit delete: a synced row's delete must stay out of the push set during the
 * undo window so a background sync cannot flush it before the user decides, and undo must restore it
 * with no server round-trip.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [33])
class TransactionRepositoryTest {

    private lateinit var db: CashflowDatabase
    private lateinit var dao: TransactionDao
    private lateinit var repository: TransactionRepository
    private val scheduler = RecordingScheduler()

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(
            RuntimeEnvironment.getApplication(),
            CashflowDatabase::class.java,
        ).allowMainThreadQueries().build()
        dao = db.transactionDao()
        repository = TransactionRepository(
            transactionDao = dao,
            categoryDao = db.categoryDao(),
            accountDao = db.accountDao(),
            templateDao = db.templateDao(),
            syncScheduler = scheduler,
        )
    }

    @After
    fun tearDown() = db.close()

    @Test
    fun `synced row delete is deferred out of dirty and requests no sync until committed`() = runTest {
        dao.upsert(synced("t1", version = 2))

        val snapshot = repository.softDeleteLocal("t1")

        assertNotNull(snapshot)
        val hidden = dao.getById("t1")!!
        assertEquals(SyncStatus.PENDING_DELETE, hidden.sync.syncStatus)
        assertNotNull(hidden.deletedAt)
        assertTrue(dao.dirty().isEmpty()) // not pushable yet
        assertEquals(0, scheduler.syncRequests) // softDelete must not flush

        repository.commitDelete("t1")

        assertEquals(SyncStatus.PENDING, dao.getById("t1")!!.sync.syncStatus)
        assertEquals(1, scheduler.syncRequests)
    }

    @Test
    fun `undo restores the original row and never requests a sync`() = runTest {
        dao.upsert(synced("t1", version = 2))
        val snapshot = repository.softDeleteLocal("t1")!!

        repository.restore(snapshot)

        val restored = dao.getById("t1")!!
        assertNull(restored.deletedAt)
        assertEquals(SyncStatus.CLEAN, restored.sync.syncStatus)

        repository.commitDelete("t1") // snackbar dismissed after an undo: nothing to commit
        assertEquals(0, scheduler.syncRequests)
    }

    @Test
    fun `never-synced create is hard-deleted immediately with no sync`() = runTest {
        dao.upsert(synced("t2", version = 0).copy(sync = SyncMeta(isSynced = false, syncStatus = SyncStatus.PENDING)))

        repository.softDeleteLocal("t2")

        assertNull(dao.getById("t2"))
        repository.commitDelete("t2")
        assertEquals(0, scheduler.syncRequests)
    }

    private fun synced(id: String, version: Int) = TransactionEntity(
        id = id, name = null, type = "expense", amount = 500, currency = "JPY",
        date = "2026-06-02T14:30:00", memo = null, categoryId = "c1", accountId = null,
        isAutoGenerated = false, isBalanceAdjustment = false, recurringTransactionId = null,
        version = version, createdAt = "2026-06-02T14:30:00", updatedAt = "2026-06-02T14:30:00",
        deletedAt = null, sync = SyncMeta(isSynced = true, syncStatus = SyncStatus.CLEAN),
    )

    private class RecordingScheduler : SyncScheduler {
        var syncRequests = 0
        override fun requestSync() { syncRequests++ }
        override fun ensurePeriodicSync() = Unit
    }
}
