package com.kakeibo.android.core.data.sync

import com.kakeibo.android.core.database.entity.AccountEntity
import com.kakeibo.android.core.database.entity.BudgetEntity
import com.kakeibo.android.core.database.entity.CategoryEntity
import com.kakeibo.android.core.database.entity.InputPatternEntity
import com.kakeibo.android.core.database.entity.NotificationSettingEntity
import com.kakeibo.android.core.database.entity.RecurringTransactionEntity
import com.kakeibo.android.core.database.entity.SyncMeta
import com.kakeibo.android.core.database.entity.SyncStatus
import com.kakeibo.android.core.database.entity.TagEntity
import com.kakeibo.android.core.database.entity.TemplateEntity
import com.kakeibo.android.core.database.entity.TransactionEntity
import com.kakeibo.android.core.database.entity.TransferEntity
import com.kakeibo.android.core.network.dto.AccountDto
import com.kakeibo.android.core.network.dto.BudgetDto
import com.kakeibo.android.core.network.dto.CategoryDto
import com.kakeibo.android.core.network.dto.InputPatternDto
import com.kakeibo.android.core.network.dto.NotificationSettingDto
import com.kakeibo.android.core.network.dto.RecurringTransactionDto
import com.kakeibo.android.core.network.dto.TagDto
import com.kakeibo.android.core.network.dto.TemplateDto
import com.kakeibo.android.core.network.dto.TransactionDto
import com.kakeibo.android.core.network.dto.TransferDto
import java.time.Instant
import java.time.OffsetDateTime

/**
 * DTO → Room entity mappers for the sync pull. Pulled rows are authoritative, so they land
 * as [SyncStatus.CLEAN]/synced. `localUpdatedAt` is seeded from the server `updated_at` so a
 * later locally-edited row can be compared against it for conflict detection (design §3.1).
 */

/** Parses an ISO-8601 timestamp to epoch millis, falling back to [fallback] when absent/invalid. */
internal fun parseEpochMillis(iso: String?, fallback: Long): Long {
    if (iso.isNullOrBlank()) return fallback
    return runCatching { OffsetDateTime.parse(iso).toInstant().toEpochMilli() }
        .recoverCatching { Instant.parse(iso).toEpochMilli() }
        .getOrDefault(fallback)
}

private fun syncedMeta(updatedAt: String?, now: Long) =
    SyncMeta(isSynced = true, syncStatus = SyncStatus.CLEAN, localUpdatedAt = parseEpochMillis(updatedAt, now))

fun AccountDto.toEntity(now: Long) = AccountEntity(
    id = id, name = name, type = type, initialBalance = initial_balance, currency = currency,
    sortOrder = sort_order, paymentDay = payment_day, balance = balance, version = version,
    createdAt = created_at, updatedAt = updated_at, deletedAt = deleted_at,
    sync = syncedMeta(updated_at, now),
)

fun CategoryDto.toEntity(now: Long) = CategoryEntity(
    id = id, name = name, type = type, icon = icon, color = color, sortOrder = sort_order,
    isDefault = is_default, version = version, createdAt = created_at, updatedAt = updated_at,
    deletedAt = deleted_at, sync = syncedMeta(updated_at, now),
)

fun TagDto.toEntity(now: Long) = TagEntity(
    id = id, name = name, color = color, version = version, createdAt = created_at,
    updatedAt = updated_at, deletedAt = deleted_at, sync = syncedMeta(updated_at, now),
)

fun TransactionDto.toEntity(now: Long) = TransactionEntity(
    id = id, name = name, type = type, amount = amount, currency = currency, date = date,
    memo = memo, categoryId = category_id, accountId = account_id,
    isAutoGenerated = is_auto_generated, isBalanceAdjustment = is_balance_adjustment,
    recurringTransactionId = recurring_transaction_id, version = version, createdAt = created_at,
    updatedAt = updated_at, deletedAt = deleted_at, sync = syncedMeta(updated_at, now),
)

fun TransferDto.toEntity(now: Long) = TransferEntity(
    id = id, fromAccountId = from_account_id, toAccountId = to_account_id, amount = amount,
    currency = currency, date = date, memo = memo, version = version, createdAt = created_at,
    updatedAt = updated_at, deletedAt = deleted_at, sync = syncedMeta(updated_at, now),
)

fun TemplateDto.toEntity(now: Long) = TemplateEntity(
    id = id, name = name, transactionName = transaction_name, type = type, amount = amount,
    currency = currency, categoryId = category_id, accountId = account_id, memo = memo,
    useCount = use_count, lastUsedAt = last_used_at, version = version, createdAt = created_at,
    updatedAt = updated_at, deletedAt = deleted_at, sync = syncedMeta(updated_at, now),
)

fun RecurringTransactionDto.toEntity(now: Long) = RecurringTransactionEntity(
    id = id, type = type, amount = amount, currency = currency, categoryId = category_id,
    accountId = account_id, memo = memo, frequency = frequency, interval = interval,
    dayOfWeek = day_of_week, dayOfMonth = day_of_month, monthOfYear = month_of_year,
    startDate = start_date, endDate = end_date, nextExecutionDate = next_execution_date,
    isActive = is_active, version = version, createdAt = created_at, updatedAt = updated_at,
    deletedAt = deleted_at, sync = syncedMeta(updated_at, now),
)

fun BudgetDto.toEntity(now: Long) = BudgetEntity(
    id = id, categoryId = category_id, yearMonth = year_month, amount = amount,
    currency = currency, version = version, createdAt = created_at, updatedAt = updated_at,
    deletedAt = deleted_at, sync = syncedMeta(updated_at, now),
)

fun NotificationSettingDto.toEntity(now: Long) = NotificationSettingEntity(
    id = id, type = type, isEnabled = is_enabled, frequency = frequency, dayOfWeek = day_of_week,
    timeOfDay = time_of_day, thresholdPercent = threshold_percent,
    reminderDaysBefore = reminder_days_before, version = version, createdAt = created_at,
    updatedAt = updated_at, sync = syncedMeta(updated_at, now),
)

fun InputPatternDto.toEntity(now: Long) = InputPatternEntity(
    id = id, keyword = keyword, categoryId = category_id, accountId = account_id,
    hitCount = hit_count, lastUsedAt = last_used_at, sync = syncedMeta(last_used_at, now),
)
